name: 'md2pdf'
description: 'Markdown を PDF・DOCX に変換（日本語・Mermaid対応）'
author: 'Linkbal Inc.'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  input_dir:
    description: 'Markdownファイルがあるディレクトリ'
    required: false
    default: 'docs'
  output_dir:
    description: '出力ディレクトリ'
    required: false
    default: 'output'
  output_formats:
    description: '出力形式（カンマ区切り: pdf,docx）'
    required: false
    default: 'pdf,docx'
  docx_template:
    description: 'DOCXテンプレートファイルのパス（リポジトリからの相対パス）'
    required: false
    default: ''
  header_tex:
    description: 'カスタムLaTeXヘッダーファイルのパス（リポジトリからの相対パス）'
    required: false
    default: ''
  upload_artifact:
    description: 'アーティファクトをアップロードするか'
    required: false
    default: 'true'
  artifact_name:
    description: 'アーティファクト名'
    required: false
    default: 'docs-output'
  retention_days:
    description: 'アーティファクトの保持日数'
    required: false
    default: '30'
  create_release:
    description: 'GitHub Releaseを作成するか'
    required: false
    default: 'false'
  release_name_prefix:
    description: 'リリース名のプレフィックス'
    required: false
    default: 'Release'
  keep_releases:
    description: '保持するリリース数（0で無制限）'
    required: false
    default: '5'
  release_as_zip:
    description: 'リリース時にZIPアーカイブにまとめるか'
    required: false
    default: 'false'
  zip_name:
    description: 'ZIPファイル名（拡張子なし）'
    required: false
    default: 'documents'

outputs:
  tag_name:
    description: '作成されたタグ名'
    value: ${{ steps.tag.outputs.name }}

runs:
  using: 'composite'
  steps:
    - name: Dockerイメージをビルド
      shell: bash
      run: |
        docker build -t md2pdf ${{ github.action_path }}/scripts

    - name: PDF・DOCXを生成
      shell: bash
      env:
        OUTPUT_FORMATS: ${{ inputs.output_formats }}
        DOCX_TEMPLATE_INPUT: ${{ inputs.docx_template }}
        HEADER_TEX_INPUT: ${{ inputs.header_tex }}
      run: |
        mkdir -p ${{ inputs.output_dir }}

        # テンプレートマウントオプションを構築
        TEMPLATE_MOUNT=""
        TEMPLATE_ENV=""
        if [ -n "$DOCX_TEMPLATE_INPUT" ] && [ -f "${{ github.workspace }}/$DOCX_TEMPLATE_INPUT" ]; then
          TEMPLATE_MOUNT="-v ${{ github.workspace }}/$DOCX_TEMPLATE_INPUT:/work/template.docx:ro"
          TEMPLATE_ENV="-e DOCX_TEMPLATE=/work/template.docx"
        fi

        # カスタムヘッダーマウントオプションを構築
        HEADER_MOUNT=""
        HEADER_ENV=""
        if [ -n "$HEADER_TEX_INPUT" ] && [ -f "${{ github.workspace }}/$HEADER_TEX_INPUT" ]; then
          HEADER_MOUNT="-v ${{ github.workspace }}/$HEADER_TEX_INPUT:/work/header.tex:ro"
          HEADER_ENV="-e HEADER_TEX=/work/header.tex"
        fi

        docker run --rm \
          -v ${{ github.workspace }}/${{ inputs.input_dir }}:/work/input:ro \
          -v ${{ github.workspace }}/${{ inputs.output_dir }}:/work/output \
          -e OUTPUT_FORMATS="$OUTPUT_FORMATS" \
          $TEMPLATE_MOUNT $TEMPLATE_ENV \
          $HEADER_MOUNT $HEADER_ENV \
          md2pdf /work/input /work/output

    - name: 生成されたファイルを確認
      shell: bash
      run: |
        echo "Generated files:"
        find ${{ inputs.output_dir }} -type f \( -name "*.pdf" -o -name "*.docx" \) -exec ls -la {} \;

    - name: アーティファクトをアップロード
      if: inputs.upload_artifact == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: |
          ${{ inputs.output_dir }}/**/*.pdf
          ${{ inputs.output_dir }}/**/*.docx
        retention-days: ${{ inputs.retention_days }}

    - name: ZIPアーカイブを作成
      if: inputs.create_release == 'true' && inputs.release_as_zip == 'true'
      shell: bash
      run: |
        cd ${{ inputs.output_dir }}
        zip -r ../${{ inputs.zip_name }}.zip .
        echo "Created ZIP archive: ${{ inputs.zip_name }}.zip"
        ls -la ../${{ inputs.zip_name }}.zip

    - name: タグを作成
      if: inputs.create_release == 'true'
      id: tag
      shell: bash
      run: |
        TAG="v$(date +'%Y%m%d')-${GITHUB_SHA::7}"
        echo "name=$TAG" >> $GITHUB_OUTPUT
        if git rev-parse --verify "refs/tags/$TAG" >/dev/null 2>&1; then
          echo "Tag $TAG already exists, skipping creation"
        else
          git tag "$TAG" && git push origin "$TAG"
        fi

    - name: リリースを作成（ZIP）
      if: inputs.create_release == 'true' && inputs.release_as_zip == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.name }}
        name: ${{ inputs.release_name_prefix }} ${{ steps.tag.outputs.name }}
        files: ${{ inputs.zip_name }}.zip
        generate_release_notes: true

    - name: リリースを作成（個別ファイル）
      if: inputs.create_release == 'true' && inputs.release_as_zip != 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.name }}
        name: ${{ inputs.release_name_prefix }} ${{ steps.tag.outputs.name }}
        files: |
          ${{ inputs.output_dir }}/**/*.pdf
          ${{ inputs.output_dir }}/**/*.docx
        generate_release_notes: true

    - name: 古いリリースを削除
      if: inputs.create_release == 'true' && inputs.keep_releases != '0'
      uses: dev-drprasad/delete-older-releases@v0.3.4
      with:
        keep_latest: ${{ inputs.keep_releases }}
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
